openapi: 3.0.4
info:
  title: Simplified Webhooks Backend
  version: '1.0'
  description: An API for registering and deleting webhooks on Airtable.
  contact:
    name: API Support
    url: 'https://api.simplified-webhooks.com/'
    email: contact@simplified-webhooks.com
servers:
  - url: ${{url}}
    description: Main server
paths:
  /webhooks/register:
    post:
      tags:
        - Webhooks
      summary: Register a new webhook
      description: This endpoint allows for the registration of a new webhook for specific events.
      operationId: registerNewWebhook
      requestBody:
        description: Webhook registration details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRegistration'
            examples:
              record_update:
                summary: Example for a record update event
                value:
                  baseId: "appkGlXEiufQLn1Qd"
                  tableId: "tblMHdKX6vN1Eci9x"
                  event: "record_update"
                  columnId:
                    - "fldAqLqTAgpBIv6HF"
                    - "fldAnotherColumnId"
                  webhookUrl: "https://hook.eu2.make.com/your-unique-hook-id"
              record_create:
                summary: Example for a record create event
                value:
                  baseId: "appkGlXEiufQLn1Qd"
                  tableId: "tblMHdKX6vN1Eci9x"
                  event: "record_create"
                  webhookUrl: "https://hook.eu1.make.com/your-unique-hook-id"
              record_delete:
                summary: Example for a record delete event
                value:
                  baseId: "appkGlXEiufQLn1Qd"
                  tableId: "tblMHdKX6vN1Eci9x"
                  event: "record_delete"
                  webhookUrl: "https://hook.eu1.make.com/your-unique-hook-id"
      responses:
        '201':
          description: Webhook registered successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Webhook registered successfully.
                  webhookId:
                    type: string
                    format: uuid
                    example: "20c775ff-666c-42d7-b4db-26e4af4e43c7"
        '400':
          description: Bad request due to invalid input.
        '401':
          description: Unauthorized, API key is missing or invalid.
      security:
        - apiKey: []
  /webhooks/delete/{webhookId}:
    delete:
      tags:
        - Webhooks
      summary: Delete a webhook
      description: This endpoint deletes an existing webhook by its ID.
      operationId: deleteWebhook
      parameters:
        - name: webhookId
          in: path
          required: true
          description: The unique identifier of the webhook to be deleted.
          schema:
            type: string
            format: uuid
            example: "20c775ff-666c-42d7-b4db-26e4af4e43c7"
      responses:
        '204':
          description: Webhook deleted successfully.
        '401':
          description: Unauthorized, API key is missing or invalid.
        '404':
          description: Webhook not found.
      security:
        - apiKey: []
components:
  schemas:
    WebhookRegistration:
      type: object
      required:
        - baseId
        - tableId
        - event
        - webhookUrl
      properties:
        baseId:
          type: string
          description: The ID of the base.
          example: "appkGlXEiufQLn1Qd"
        tableId:
          type: string
          description: The ID of the table.
          example: "tblMHdKX6vN1Eci9x"
        event:
          type: string
          description: The type of event to subscribe to.
          enum:
            - "record_update"
            - "record_create"
            - "record_delete"
        columnId:
          type: array
          items:
            type: string
            example: "fldAqLqTAgpBIv6HF"
          description: An array of column IDs to watch for updates. This field is only applicable for the 'record_update' event.
        webhookUrl:
          type: string
          format: uri
          description: The URL to which the webhook notifications will be sent.
          example: "https://hook.eu2.make.com/your-unique-hook-id"
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Authorization
      description: API key for authentication.
